create database employee ;
use employee;
create table emp(ecode int,ename varchar(10),phone int CHECK (phone>688880),depart varchar(10));
insert into emp values(1," krish ",999999,"dosa");
insert into emp values(22,"vani",8888,"dora");
insert into emp values(44,"  radha",8878,"dofa");
insert into emp values(35,"radhika ",45670,"media");
insert into emp values(77,"girl",7777,"dora");
select * from emp ;
Alter table emp add sal float(8,2);
Update emp set sal =1000;
select * from emp;
Update emp set sal = sal+500 where depart='dora';
select * from emp;
select upper(ename) from emp;
select length('  Informatics  Practices  ');
select length(trim('  Informatics  Practices  '));
select upper(substr('Informatics  Practices',3,4));
select instr('Informatics Practices','TI');
alter table emp modify ename varchar(20);